In [1]:
import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv('./train.csv')
test = pd.read_csv('./test.csv')
columns = ['ID',
             'Subscription_Length',
             'Voice_Mailbox_Usage',
             'Early_Call_Length',
             'Early_Calls_Freq',
             'Early_Call_Fee',
             'Late_Call_Length',
             'Late_Calls_Freq',
             'Late_Call_Fee',
             'Night_Call_Length',
             'Night_Calls_Freq',
             'Night_Call_Fee',
             'Counseling_Calls',
             'Cancellation_Status']
train.columns = columns
test.columns = columns[:13]
train

ID  Subscription_Length  Voice_Mailbox_Usage  \
0      TRAIN_00000                  329                    0   
1      TRAIN_00001                    2                   80   
2      TRAIN_00002                   93                   28   
3      TRAIN_00003                  223                    1   
4      TRAIN_00004                  222                    0   
...            ...                  ...                  ...   
30195  TRAIN_30195                  263                   80   
30196  TRAIN_30196                  283                   81   
30197  TRAIN_30197                   24                    0   
30198  TRAIN_30198                   63                    1   
30199  TRAIN_30199                  200                    1   

       Early_Call_Length  Early_Calls_Freq  Early_Call_Fee  Late_Call_Length  \
0                   99.2                93            27.3             268.8   
1                  323.9               323            83.7             269.4   
2                  282.4               323            34.2             207.0   
3                  221.4               223            25.1             233.0   
4                   96.3               222            28.7             223.9   
...                  ...               ...             ...               ...   
30195              289.6               201            21.8             280.5   
30196              210.7               280            90.5             284.1   
30197              222.4                33            22.1             233.9   
30198              262.4               202            29.6             280.6   
30199              327.1               203            86.8             330.1   

       Late_Calls_Freq  Late_Call_Fee  Night_Call_Length  Night_Calls_Freq  \
0                   68          28.92              262.9               328   
1                  326          32.09              322.8               209   
2                  322          32.82              280.8               328   
3                   61          23.90              203.8               234   
4                   69          28.08              263.1               223   
...                ...            ...                ...               ...   
30195              323          29.88              208.0                66   
30196              202          32.80              287.8               203   
30197               32          22.22              293.6                95   
30198              282          28.88              280.9               207   
30199               82          28.88              289.1               323   

       Night_Call_Fee  Counseling_Calls  Cancellation_Status  
0               32.89                 2                    0  
1               32.32                 2                    0  
2                8.28                 0                    0  
3                9.36                 0                    0  
4                2.80                 8                    0  
...               ...               ...                  ...  
30195            9.28                 2                    0  
30196            6.28                 2                    0  
30197            4.22                 2                    0  
30198           20.88                 2                    1  
30199            6.28                 0                    0  

[30200 rows x 14 columns]

In [3]:
# main_time = []
# for i in train.loc[:,['Early_Call_Length','Late_Call_Length','Night_Call_Length']].values:
#     i = list(i)
#     main_time.append(i.index(max(i)))
# train['main_time'] = main_time    

# main_time = []
# for i in test.loc[:,['Early_Call_Length','Late_Call_Length','Night_Call_Length']].values:
#     i = list(i)
#     main_time.append(i.index(max(i)))
# test['main_time'] = main_time    


In [4]:
train.corr()

C:\Users\user\AppData\Local\Temp\ipykernel_29556\2189804198.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  train.corr()


Subscription_Length  Voice_Mailbox_Usage  \
Subscription_Length             1.000000             0.069771   
Voice_Mailbox_Usage             0.069771             1.000000   
Early_Call_Length               0.190535             0.045449   
Early_Calls_Freq                0.128138             0.031312   
Early_Call_Fee                  0.118500             0.070361   
Late_Call_Length                0.223365             0.067955   
Late_Calls_Freq                 0.119532             0.039927   
Late_Call_Fee                   0.208486             0.065085   
Night_Call_Length               0.256722             0.068964   
Night_Calls_Freq                0.111628             0.052887   
Night_Call_Fee                  0.064803             0.025955   
Counseling_Calls                0.073547             0.010326   
Cancellation_Status             0.006688            -0.062734   

                     Early_Call_Length  Early_Calls_Freq  Early_Call_Fee  \
Subscription_Length           0.190535          0.128138        0.118500   
Voice_Mailbox_Usage           0.045449          0.031312        0.070361   
Early_Call_Length             1.000000          0.213815        0.336852   
Early_Calls_Freq              0.213815          1.000000        0.100227   
Early_Call_Fee                0.336852          0.100227        1.000000   
Late_Call_Length              0.493299          0.265814        0.219930   
Late_Calls_Freq               0.239448          0.147605        0.098014   
Late_Call_Fee                 0.483473          0.247990        0.216840   
Night_Call_Length             0.508642          0.289059        0.219115   
Night_Calls_Freq              0.238676          0.109052        0.126778   
Night_Call_Fee                0.177415          0.102214        0.075288   
Counseling_Calls              0.158215          0.072544        0.102932   
Cancellation_Status           0.029975          0.010974       -0.071006   

                     Late_Call_Length  Late_Calls_Freq  Late_Call_Fee  \
Subscription_Length          0.223365         0.119532       0.208486   
Voice_Mailbox_Usage          0.067955         0.039927       0.065085   
Early_Call_Length            0.493299         0.239448       0.483473   
Early_Calls_Freq             0.265814         0.147605       0.247990   
Early_Call_Fee               0.219930         0.098014       0.216840   
Late_Call_Length             1.000000         0.280098       0.806827   
Late_Calls_Freq              0.280098         1.000000       0.278620   
Late_Call_Fee                0.806827         0.278620       1.000000   
Night_Call_Length            0.605980         0.277744       0.580330   
Night_Calls_Freq             0.276678         0.135633       0.272802   
Night_Call_Fee               0.210535         0.094207       0.204482   
Counseling_Calls             0.189158         0.080626       0.189227   
Cancellation_Status         -0.000163        -0.004276       0.001711   

                     Night_Call_Length  Night_Calls_Freq  Night_Call_Fee  \
Subscription_Length           0.256722          0.111628        0.064803   
Voice_Mailbox_Usage           0.068964          0.052887        0.025955   
Early_Call_Length             0.508642          0.238676        0.177415   
Early_Calls_Freq              0.289059          0.109052        0.102214   
Early_Call_Fee                0.219115          0.126778        0.075288   
Late_Call_Length              0.605980          0.276678        0.210535   
Late_Calls_Freq               0.277744          0.135633        0.094207   
Late_Call_Fee                 0.580330          0.272802        0.204482   
Night_Call_Length             1.000000          0.286981        0.305315   
Night_Calls_Freq              0.286981          1.000000        0.083941   
Night_Call_Fee                0.305315          0.083941        1.000000   
Counseling_Calls              0.191133          0.083491        0.043592   
Cancellation_Status          -0.00

In [5]:
from catboost import CatBoostClassifier
from sklearn.model_selection import KFold, StratifiedKFold
from sklearn.metrics import accuracy_score, f1_score
from tqdm import tqdm
kf = KFold(n_splits = 10, random_state = 42, shuffle = True)

parms = {'iterations': 2000,
 #'od_wait': 2182,
 'learning_rate': 0.005,
 #'reg_lambda': 2.3132945175291226,
 #'subsample': 0.01621008882000844,
 #'random_strength': 25.292157882359646,
 'depth': 5,
 'min_data_in_leaf': 5,
 #'leaf_estimation_iterations': 3,
 'bagging_temperature': 0.01080117689593031,
 'colsample_bylevel': 0.7579360851684404}

target = 'Cancellation_Status'
features = [c for c in train.columns if c not in ['ID', target]]
models = []
val_scores = []

for i, (train_index, val_index) in tqdm(enumerate(kf.split(train, train[target]))):
    
    X_train, X_val = train[features].loc[train_index], train[features].loc[val_index]
    y_train, y_val = train[target][train_index], train[target][val_index]
    
#     if include_orig:
#         X_train = X_train.append(original[features], ignore_index = True)
#         y_train = y_train.append(original[target], ignore_index = True)
    
    model = CatBoostClassifier(random_state = 42)
    
    model.fit(X_train, y_train, eval_set = [(X_val, y_val)], verbose = 2000)
    
    models.append(model)
    pred = model.predict(X_val)
    score = f1_score(y_val, pred)
    val_scores.append(score)
    
    print(f'ACC on fold {i}: {score:.4f}')
    
print(f'mean ACC across all folds: {np.mean(val_scores):.4f}')





# cat = catboost.CatBoostClassifier(**parms)
# cat.fit(train.drop(['ID','Cancellation_Status'],axis=1),train['Cancellation_Status'])
# pred = cat.predict(test.drop('ID',axis=1))

0it [00:00, ?it/s]C:\Users\user\anaconda3\envs\pycaret\lib\site-packages\catboost\core.py:1411: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,


Learning rate set to 0.071642
0:	learn: 0.6350188	test: 0.6340113	best: 0.6340113 (0)	total: 161ms	remaining: 2m 41s


1it [00:03,  3.89s/it]

999:	learn: 0.1343973	test: 0.2016039	best: 0.2016039 (999)	total: 3.69s	remaining: 0us

bestTest = 0.2016038763
bestIteration = 999

ACC on fold 0: 0.4092
Learning rate set to 0.071642
0:	learn: 0.6350396	test: 0.6338996	best: 0.6338996 (0)	total: 31.9ms	remaining: 31.9s


C:\Users\user\anaconda3\envs\pycaret\lib\site-packages\catboost\core.py:1411: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
2it [00:07,  3.78s/it]

999:	learn: 0.1335060	test: 0.1989680	best: 0.1989680 (999)	total: 3.57s	remaining: 0us

bestTest = 0.1989680068
bestIteration = 999

ACC on fold 1: 0.3880
Learning rate set to 0.071642
0:	learn: 0.6349478	test: 0.6345091	best: 0.6345091 (0)	total: 13.5ms	remaining: 13.5s


C:\Users\user\anaconda3\envs\pycaret\lib\site-packages\catboost\core.py:1411: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
3it [00:11,  3.73s/it]

999:	learn: 0.1355505	test: 0.2022965	best: 0.2022485 (992)	total: 3.52s	remaining: 0us

bestTest = 0.2022484782
bestIteration = 992

Shrink model to first 993 iterations.
ACC on fold 2: 0.4046
Learning rate set to 0.071642
0:	learn: 0.6345822	test: 0.6358031	best: 0.6358031 (0)	total: 7.68ms	remaining: 7.67s


C:\Users\user\anaconda3\envs\pycaret\lib\site-packages\catboost\core.py:1411: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
4it [00:14,  3.69s/it]

999:	learn: 0.1331005	test: 0.2206553	best: 0.2206553 (999)	total: 3.5s	remaining: 0us

bestTest = 0.2206552802
bestIteration = 999

ACC on fold 3: 0.3753
Learning rate set to 0.071642
0:	learn: 0.6345258	test: 0.6357491	best: 0.6357491 (0)	total: 11.9ms	remaining: 11.9s


C:\Users\user\anaconda3\envs\pycaret\lib\site-packages\catboost\core.py:1411: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
5it [00:18,  3.70s/it]

999:	learn: 0.1321355	test: 0.2165157	best: 0.2165058 (997)	total: 3.57s	remaining: 0us

bestTest = 0.216505836
bestIteration = 997

Shrink model to first 998 iterations.
ACC on fold 4: 0.4219
Learning rate set to 0.071642
0:	learn: 0.6342066	test: 0.6366513	best: 0.6366513 (0)	total: 12.2ms	remaining: 12.2s


C:\Users\user\anaconda3\envs\pycaret\lib\site-packages\catboost\core.py:1411: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
6it [00:22,  3.68s/it]

999:	learn: 0.1336638	test: 0.2242459	best: 0.2242459 (999)	total: 3.5s	remaining: 0us

bestTest = 0.2242458501
bestIteration = 999

ACC on fold 5: 0.4271
Learning rate set to 0.071642
0:	learn: 0.6344336	test: 0.6357530	best: 0.6357530 (0)	total: 23.4ms	remaining: 23.3s


C:\Users\user\anaconda3\envs\pycaret\lib\site-packages\catboost\core.py:1411: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
7it [00:25,  3.67s/it]

999:	learn: 0.1354708	test: 0.2227606	best: 0.2227387 (998)	total: 3.51s	remaining: 0us

bestTest = 0.2227387265
bestIteration = 998

Shrink model to first 999 iterations.
ACC on fold 6: 0.4074
Learning rate set to 0.071642
0:	learn: 0.6348555	test: 0.6344183	best: 0.6344183 (0)	total: 12.5ms	remaining: 12.4s


C:\Users\user\anaconda3\envs\pycaret\lib\site-packages\catboost\core.py:1411: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
8it [00:29,  3.66s/it]

999:	learn: 0.1341677	test: 0.2122737	best: 0.2122724 (997)	total: 3.51s	remaining: 0us

bestTest = 0.2122724416
bestIteration = 997

Shrink model to first 998 iterations.
ACC on fold 7: 0.4018
Learning rate set to 0.071642
0:	learn: 0.6351407	test: 0.6339402	best: 0.6339402 (0)	total: 23.3ms	remaining: 23.2s


C:\Users\user\anaconda3\envs\pycaret\lib\site-packages\catboost\core.py:1411: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
9it [00:33,  3.67s/it]

999:	learn: 0.1339172	test: 0.2014627	best: 0.2014627 (999)	total: 3.55s	remaining: 0us

bestTest = 0.2014626843
bestIteration = 999

ACC on fold 8: 0.4065
Learning rate set to 0.071642
0:	learn: 0.6348430	test: 0.6346584	best: 0.6346584 (0)	total: 22ms	remaining: 21.9s


C:\Users\user\anaconda3\envs\pycaret\lib\site-packages\catboost\core.py:1411: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
10it [00:36,  3.68s/it]

999:	learn: 0.1336804	test: 0.2125914	best: 0.2124914 (997)	total: 3.48s	remaining: 0us

bestTest = 0.2124914009
bestIteration = 997

Shrink model to first 998 iterations.
ACC on fold 9: 0.3524
mean ACC across all folds: 0.3994


In [6]:
cat_preds = []

for model in models[:10]:
    preds = model.predict_proba(test[features])[:,1]
    cat_preds.append(preds)

C:\Users\user\anaconda3\envs\pycaret\lib\site-packages\catboost\core.py:1411: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
C:\Users\user\anaconda3\envs\pycaret\lib\site-packages\catboost\core.py:1411: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
C:\Users\user\anaconda3\envs\pycaret\lib\site-packages\catboost\core.py:1411: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
C:\Users\user\anaconda3\envs\pycaret\lib\site-packages\catboost\core.py:1411: FutureWarning: iteritems is 

In [ ]:
# train = train.drop('Counseling_Calls',axis=1)
# from pycaret import classification
# classification.setup(data=train,target='Cancellation_Status')

In [ ]:
# best = classification.compare_models(sort='ACC',n_select=4,fold=10)

In [21]:
kf = StratifiedKFold(n_splits = 10, random_state = 1, shuffle = True)
val_scores = []

params = {'scale_pos_weight': 2,
 #'lambda_l2': 14.705798704172345,
 'num_leaves': 10,
 'learning_rate': 0.005,
 #'feature_fraction': 0.8402041342033796,
 #'bagging_fraction': 0.5053012488246705,
 'bagging_freq': 5,
 'min_child_samples': 10,
 'min_data_in_leaf': 10,
 'max_depth': 10,
 'random_state' : 41}
# params = study.best_params

for i, (train_index, val_index) in tqdm(enumerate(kf.split(train, train[target]))):
    
    X_train, X_val = train[features].loc[train_index], train[features].loc[val_index]
    y_train, y_val = train[target][train_index], train[target][val_index]
    
#     if include_orig:
#         X_train = X_train.append(original[features], ignore_index = True)
#         y_train = y_train.append(original[target], ignore_index = True)
    
    model = LGBMClassifier(**params)
    
    model.fit(X_train, y_train)
    
    models.append(model)
    pred = model.predict(X_val)
    score = f1_score(y_val, pred)

    val_scores.append(score)
    
    print(f'score on fold {i}: {score:.4f}')
    
print(f'mean score across all folds: {np.mean(val_scores):.4f}')

0it [00:00, ?it/s]


NameError: name 'LGBMClassifier' is not defined

In [11]:
cat_preds

[array([0.04956605, 0.10572691, 0.01455392, ..., 0.07925392, 0.09297478,
        0.06341146]),
 array([0.04565547, 0.05503563, 0.00849989, ..., 0.07955225, 0.1340641 ,
        0.08812596]),
 array([0.03576755, 0.08553582, 0.0189477 , ..., 0.07434654, 0.11768232,
        0.15595464]),
 array([0.05660247, 0.07726497, 0.00678296, ..., 0.08679874, 0.06868064,
        0.07539045]),
 array([0.03777025, 0.07142083, 0.00810559, ..., 0.04743862, 0.06812209,
        0.10136861]),
 array([0.04172581, 0.07542723, 0.02004105, ..., 0.08450697, 0.07066018,
        0.16716572]),
 array([0.05589673, 0.06340281, 0.01244166, ..., 0.07470671, 0.06919991,
        0.13057917]),
 array([0.03266533, 0.09154767, 0.02579132, ..., 0.05984498, 0.10929758,
        0.07275611]),
 array([0.04901826, 0.05305101, 0.02190852, ..., 0.08006557, 0.08996281,
        0.12413609]),
 array([0.04365132, 0.09055362, 0.01442186, ..., 0.07360011, 0.09898188,
        0.08883802])]

In [43]:
target = []
for i in np.array(cat_preds).mean(axis=0):
    if i < 0.21:
        target.append(0)
    else:
        target.append(1)

In [44]:
sample = pd.read_csv('./sample_submission.csv',index_col='ID')
sample['전화해지여부'] = target
sample.to_csv('./submission.csv')

In [45]:
sample['전화해지여부'].value_counts()


0    11345
1     1598
Name: 전화해지여부, dtype: int64

In [46]:
train['Cancellation_Status'].value_counts()

0    26882
1     3318
Name: Cancellation_Status, dtype: int64

In [49]:
1598/len(sample)

0.12346442092250637

In [50]:
3318/len(train)

0.10986754966887417